version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: tutoria_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  tutoria-api:
    build: .
    container_name: tutoria-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/tutoria_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword

volumes:
  mariadb_data:
